; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File for Raspberry Pi Pico 2
; PlatformIO Project Configuration File for Pico 2 (Official Mbed Core method)

; PlatformIO Project Configuration File for Raspberry Pi Pico 2 (RP2350)
; PlatformIO Project Configuration File for NodeMCU ESP32
[env:nodemcu-32s]
platform = espressif32
board = nodemcu-32s
framework = arduino   

; Set the serial baud rate for your Serial Monitor
monitor_speed = 115200

lib_deps =
    adafruit/DHT sensor library @ ^1.4.7
    adafruit/Adafruit Unified Sensor @ ^1.1.14